matrix:
  include:
  - dist: xenial
    language: minimal
    os: linux
    services:
    - docker
  - language: minimal
    os: osx
    osx_image: xcode10.2
script:
- ./script/download-mmdb.sh
- ./script/build-travis-${TRAVIS_OS_NAME}.sh
